/* tslint:disable */
/* eslint-disable */
/**
 * Streams
 * Streams API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: nathanfaucett@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsAnswerST
 */
export interface ModelsAnswerST {
    /**
     * 
     * @type {string}
     * @memberof ModelsAnswerST
     */
    answer_base64: string;
}

/**
 * Check if a given object implements the ModelsAnswerST interface.
 */
export function instanceOfModelsAnswerST(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "answer_base64" in value;

    return isInstance;
}

export function ModelsAnswerSTFromJSON(json: any): ModelsAnswerST {
    return ModelsAnswerSTFromJSONTyped(json, false);
}

export function ModelsAnswerSTFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsAnswerST {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'answer_base64': json['answer_base64'],
    };
}

export function ModelsAnswerSTToJSON(value?: ModelsAnswerST | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'answer_base64': value.answer_base64,
    };
}

