/* tslint:disable */
/* eslint-disable */
/**
 * Streams
 * Streams API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: nathanfaucett@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsOfferBodyST
 */
export interface ModelsOfferBodyST {
    /**
     * 
     * @type {string}
     * @memberof ModelsOfferBodyST
     */
    offer_base64: string;
}

/**
 * Check if a given object implements the ModelsOfferBodyST interface.
 */
export function instanceOfModelsOfferBodyST(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "offer_base64" in value;

    return isInstance;
}

export function ModelsOfferBodySTFromJSON(json: any): ModelsOfferBodyST {
    return ModelsOfferBodySTFromJSONTyped(json, false);
}

export function ModelsOfferBodySTFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsOfferBodyST {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offer_base64': json['offer_base64'],
    };
}

export function ModelsOfferBodySTToJSON(value?: ModelsOfferBodyST | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offer_base64': value.offer_base64,
    };
}

