/* tslint:disable */
/* eslint-disable */
/**
 * Streams
 * Streams API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: nathanfaucett@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsResponseErrorST
 */
export interface ModelsResponseErrorST {
    /**
     * 
     * @type {string}
     * @memberof ModelsResponseErrorST
     */
    error: string;
}

/**
 * Check if a given object implements the ModelsResponseErrorST interface.
 */
export function instanceOfModelsResponseErrorST(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function ModelsResponseErrorSTFromJSON(json: any): ModelsResponseErrorST {
    return ModelsResponseErrorSTFromJSONTyped(json, false);
}

export function ModelsResponseErrorSTFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsResponseErrorST {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function ModelsResponseErrorSTToJSON(value?: ModelsResponseErrorST | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

